const KEY="sm_portfolio_data_v1", PASSKEY="sm_admin_password_v1";
const defaults={name:"Sabin Maruhe",email:"maruhesabin@gmail.com",phone:"0845360603",location:"Goma, Nord-Kivu, RDC",accent:"#e8ff3f",bg:"#0a0b0f",font:"Inter",profile:"",background:"",socials:[{name:"Instagram",url:"https://instagram.com/"},{name:"Facebook",url:"https://facebook.com/"},{name:"YouTube",url:"https://youtube.com/"},{name:"TikTok",url:"https://tiktok.com/"},{name:"Telegram",url:"https://t.me/"}],projects:[{title:"Identité visuelle",description:"Création d'une identité visuelle moderne et cohérente.",image:""},{title:"Direction artistique",description:"Conception graphique et communication visuelle.",image:""},{title:"Expérience multimédia",description:"Projets numériques et expériences interactives.",image:""}],messages:[]};
const INITIAL_PASSWORD="KUNLABORU2026#2006";
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return {...defaults}}}
function save(d){localStorage.setItem(KEY,JSON.stringify(d))}
function pass(){return localStorage.getItem(PASSKEY)||INITIAL_PASSWORD}
const loginPanel=document.getElementById("loginPanel"),dash=document.getElementById("dashboard");
document.getElementById("loginForm").addEventListener("submit",e=>{e.preventDefault();if(passwordInput.value===pass()){sessionStorage.setItem("sm_admin_auth","1");showDash()}else loginError.textContent="Pasvorto malĝusta."});
if(sessionStorage.getItem("sm_admin_auth")==="1")showDash();
function showDash(){loginPanel.classList.add("hidden");dash.classList.remove("hidden");render()}
document.getElementById("logoutBtn").onclick=()=>{sessionStorage.removeItem("sm_admin_auth");dash.classList.add("hidden");loginPanel.classList.remove("hidden");passwordInput.value="";setTimeout(()=>passwordInput.focus(),50)}
function render(){const d=load();aName.value=d.name;aEmail.value=d.email;aPhone.value=d.phone;aLocation.value=d.location;aAccent.value=d.accent;aBg.value=d.bg;aFont.value=d.font;profilePreview.src=d.profile||"";bgPreview.src=d.background||"";renderSocials(d);renderProjects(d);renderMessages(d)}
function renderSocials(d){socialEditor.innerHTML=d.socials.map((s,i)=>`<div class="editor-item"><div class="row"><input data-s="${i}" data-k="name" value="${esc(s.name)}" placeholder="Platformo"><input data-s="${i}" data-k="url" value="${esc(s.url)}" placeholder="URL"></div><div class="editor-actions"><button class="mini-btn danger" onclick="removeSocial(${i})">Forigi</button></div></div>`).join("")}
function renderProjects(d){projectEditor.innerHTML=d.projects.map((p,i)=>`<div class="editor-item"><div class="row"><input data-p="${i}" data-k="title" value="${esc(p.title)}" placeholder="Titolo"><input type="file" accept="image/*" onchange="projectImage(${i},this)"></div><textarea data-p="${i}" data-k="description" rows="3" placeholder="Priskribo">${esc(p.description)}</textarea>${p.image?`<img class="preview-image" src="${p.image}">`:""}<div class="editor-actions"><button class="mini-btn danger" onclick="removeProject(${i})">Forigi projekton</button></div></div>`).join("")}
function renderMessages(d){messagesEditor.innerHTML=d.messages.length?d.messages.slice().reverse().map(m=>`<div class="editor-item"><b>${esc(m.name)}</b> <small>${esc(m.email)} — ${esc(m.date)}</small><p>${esc(m.message)}</p></div>`).join(""):"<p class='security-note'>Neniu mesaĝo ankoraŭ.</p>"}
function esc(x=""){return x.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
document.getElementById("addSocial").onclick=()=>{const d=load();d.socials.push({name:"Nova platformo",url:"https://"});save(d);render()};
window.removeSocial=i=>{const d=load();d.socials.splice(i,1);save(d);render()};
document.getElementById("addProject").onclick=()=>{const d=load();d.projects.push({title:"Nova projekto",description:"Priskribo de la projekto.",image:""});save(d);render()};
window.removeProject=i=>{const d=load();d.projects.splice(i,1);save(d);render()};
window.projectImage=(i,input)=>{const f=input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{const d=load();d.projects[i].image=r.result;save(d);render()};r.readAsDataURL(f)}
document.getElementById("profileFile").onchange=e=>readFile(e.target.files[0],v=>{const d=load();d.profile=v;save(d);render()});
document.getElementById("bgFile").onchange=e=>readFile(e.target.files[0],v=>{const d=load();d.background=v;save(d);render()});
function readFile(f,cb){if(!f)return;const r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(f)}
document.getElementById("saveBtn").onclick=()=>{const d=load();d.name=aName.value;d.email=aEmail.value;d.phone=aPhone.value;d.location=aLocation.value;d.accent=aAccent.value;d.bg=aBg.value;d.font=aFont.value;document.querySelectorAll("[data-s]").forEach(x=>d.socials[+x.dataset.s][x.dataset.k]=x.value);document.querySelectorAll("[data-p]").forEach(x=>d.projects[+x.dataset.p][x.dataset.k]=x.value);save(d);saveState.textContent="✓ Ŝanĝoj konservitaj en ĉi tiu retumilo.";render()};
document.getElementById("changePassword").onclick=()=>{if(oldPassword.value!==pass()){passwordStatus.textContent="Malnova pasvorto malĝusta.";return}if(newPassword.value.length<8){passwordStatus.textContent="Uzu almenaŭ 8 signojn.";return}localStorage.setItem(PASSKEY,newPassword.value);oldPassword.value="";newPassword.value="";passwordStatus.textContent="✓ Pasvorto ŝanĝita."}
