const KEY="sm_portfolio_data_v1";
const defaults={name:"Sabin Maruhe",email:"maruhesabin@gmail.com",phone:"0845360603",location:"Goma, Nord-Kivu, RDC",accent:"#e8ff3f",bg:"#0a0b0f",font:"Inter",profile:"",background:"",socials:[{name:"Instagram",url:"https://instagram.com/"},{name:"Facebook",url:"https://facebook.com/"},{name:"YouTube",url:"https://youtube.com/"},{name:"TikTok",url:"https://tiktok.com/"},{name:"Telegram",url:"https://t.me/"}],projects:[{title:"Identité visuelle",description:"Création d'une identité visuelle moderne et cohérente.",image:""},{title:"Direction artistique",description:"Conception graphique et communication visuelle.",image:""},{title:"Expérience multimédia",description:"Projets numériques et expériences interactives.",image:""}],messages:[]};
function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(KEY)||"{}")}}catch{return {...defaults}}}
function save(d){localStorage.setItem(KEY,JSON.stringify(d))}
const d=load();
document.documentElement.style.setProperty("--accent",d.accent);document.documentElement.style.setProperty("--bg",d.bg);document.documentElement.style.setProperty("--text","#f3f2ed");document.body.style.fontFamily=d.font;
if(d.background)document.body.style.backgroundImage=`linear-gradient(rgba(10,11,15,.82),rgba(10,11,15,.9)),url("${d.background}")`;
const pg=document.getElementById("projectGrid");
if(pg){pg.innerHTML=d.projects.map((p,i)=>`<article class="project-card reveal"><img src="${p.image||'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%22800%22 height=%22500%22%3E%3Crect width=%22100%25%22 height=%22100%25%22 fill=%22%23181b24%22/%3E%3Ctext x=%2250%25%22 y=%2250%25%22 fill=%22%23e8ff3f%22 font-size=%2250%22 text-anchor=%22middle%22%3ESM%3C/text%3E%3C/svg%3E'}" alt=""><div class="project-info"><h3>${escapeHtml(p.title)}</h3><p>${escapeHtml(p.description)}</p></div></article>`).join("")}
document.getElementById("emailText")?.replaceChildren(d.email);document.getElementById("phoneText")?.replaceChildren(d.phone);document.getElementById("locationText")?.replaceChildren(d.location);
const social=document.getElementById("socialLinks");if(social)social.innerHTML=d.socials.filter(s=>s.url).map(s=>`<a href="${s.url}" target="_blank" rel="noopener" class="btn secondary">${escapeHtml(s.name)} ↗</a>`).join(" ");
const form=document.getElementById("contactForm");form?.addEventListener("submit",e=>{e.preventDefault();const data=load();data.messages.push({name:senderName.value,email:senderEmail.value,message:senderMessage.value,date:new Date().toLocaleString()});save(data);formStatus.textContent="Mesaĝo ricevita. Dankon!";form.reset()});
function escapeHtml(x=""){return x.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}