const DEFAULTS={heroTitle:'Unu lingvo.<br><span>Miloj da ligoj.</span>',heroText:'Esperanto kunigas homojn trans limoj per simpla ideo: ni povas komuniki, lerni kaj krei kune, respektante ĉiun kulturon.',aboutTitle:'Esperanto estas pli ol lingvo.<br><em>Ĝi estas ponto.</em>',aboutText:'Ĝi donas al homoj el malsamaj landoj neŭtralan spacon por renkontiĝi. La celo ne estas anstataŭigi kulturajn lingvojn, sed aldoni komunan kanalon por internaciaj rilatoj.',phone:'+243 000 000 000',email:'contacto@example.com',contactCta:'KONTAKTU SABIN',accent:'#009e60',accent2:'#00d9ff',accent3:'#baff4a',motion:'soft'};
const KEY='esperanto-vivo-config-v2', MSG='esperanto-vivo-messages-v2';
let config={...DEFAULTS,...JSON.parse(localStorage.getItem(KEY)||'{}')};
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
function apply(){document.documentElement.style.setProperty('--accent',config.accent);document.documentElement.style.setProperty('--accent2',config.accent2);document.documentElement.style.setProperty('--accent3',config.accent3);$('#heroTitle').innerHTML=config.heroTitle;$('#heroText').textContent=config.heroText;$('#aboutTitle').innerHTML=config.aboutTitle;$('#aboutText').textContent=config.aboutText;$('#phoneLink').textContent='☎ '+config.phone;$('#phoneLink').href='tel:'+config.phone.replace(/[^+\d]/g,'');$('#emailLink').textContent='✉ '+config.email;$('#emailLink').href='mailto:'+config.email;$$('[data-key]').forEach(el=>{if(el.type==='color'||el.tagName==='SELECT'||el.tagName==='INPUT'||el.tagName==='TEXTAREA')el.value=config[el.dataset.key]??''});document.body.dataset.motion=config.motion;localStorage.setItem(KEY,JSON.stringify(config));}
apply();$('#year').textContent=new Date().getFullYear();
$('#burger').onclick=()=>$('#navLinks').classList.toggle('open');
$$('.nav-links a').forEach(a=>a.onclick=()=>$('#navLinks').classList.remove('open'));
window.addEventListener('scroll',()=>{const h=document.documentElement;$('#progress').style.width=(h.scrollTop/(h.scrollHeight-h.clientHeight)*100)+'%'});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});$$('.reveal').forEach(x=>io.observe(x));
$$('.magnetic').forEach(btn=>btn.addEventListener('pointermove',e=>{const r=btn.getBoundingClientRect();btn.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.08}px,${(e.clientY-r.top-r.height/2)*.08}px)`}));$$('.magnetic').forEach(btn=>btn.addEventListener('pointerleave',()=>btn.style.transform=''));
$('#syncBtn').onclick=()=>{apply();$('#syncBtn').animate([{transform:'rotate(0)'},{transform:'rotate(360deg)'}],{duration:500});};
function getMessages(){return JSON.parse(localStorage.getItem(MSG)||'[]')}
$('#contactForm').onsubmit=e=>{e.preventDefault();const m={email:$('#formEmail').value,subject:$('#formSubject').value,message:$('#formMessage').value,date:new Date().toLocaleString('eo-FR')};const list=getMessages();list.unshift(m);localStorage.setItem(MSG,JSON.stringify(list));$('#formStatus').textContent='Via mesaĝo estis registrita. Dankon!';e.target.reset();};
const dlg=$('#adminDialog');$('#adminBtn').onclick=()=>{dlg.showModal();$('#loginPanel').hidden=false;$('#adminPanel').hidden=true;};$('#closeAdmin').onclick=()=>dlg.close();
$('#loginForm').onsubmit=e=>{e.preventDefault();if($('#adminPassword').value==='KUNLABORADU#2020'){$('#loginPanel').hidden=true;$('#adminPanel').hidden=false;loadAdmin();renderMessages();}else $('#loginError').textContent='Pasvorto malĝusta.'};
function loadAdmin(){$$('[data-key]').forEach(el=>el.value=config[el.dataset.key]??'')}
$('#logoutBtn').onclick=()=>{dlg.close()};
$$('.admin-tabs button').forEach(b=>b.onclick=()=>{$$('.admin-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tab').forEach(t=>t.hidden=true);$('#tab-'+b.dataset.tab).hidden=false;});
$('#saveBtn').onclick=()=>{config={...config};$$('[data-key]').forEach(el=>config[el.dataset.key]=el.value);apply();$('#syncStatus').textContent='Ŝanĝoj konservitaj kaj aplikitaj al ĉi tiu retumilo.';};
$('#exportBtn').onclick=()=>{const payload={config,messages:getMessages(),exportedAt:new Date().toISOString()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='esperanto-vivo-sinkronigo.json';a.click();URL.revokeObjectURL(a.href)};
$('#importInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text());if(d.config){config={...DEFAULTS,...d.config};apply()}if(Array.isArray(d.messages))localStorage.setItem(MSG,JSON.stringify(d.messages));$('#syncStatus').textContent='Importo finita.';renderMessages()}catch{$('#syncStatus').textContent='Nevalida JSON-dosiero.'}};
$('#clearBtn').onclick=()=>{if(confirm('Ĉu restarigi la defaŭltan enhavon?')){config={...DEFAULTS};apply();loadAdmin();$('#syncStatus').textContent='Defaŭlta enhavo restarigita.'}};
function renderMessages(){const box=$('#messagesList'),list=getMessages();box.innerHTML=list.length?list.map(m=>`<article class="message-item"><b>${esc(m.subject)}</b><div>${esc(m.email)} · ${esc(m.date)}</div><p>${esc(m.message)}</p></article>`).join(''):'<p class="hint">Neniu mesaĝo ankoraŭ.</p>'}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
